Repository boostcamp-2020/Project15-A-Client-Based-Formula-Editor, pull requests merged in 2020-12, with the labels that each got.

#89 Feature/#83/dragndrop
  package-lock.json
  package.json
  src/components/LeftSection/InputSelectionSection/Box.tsx
  src/components/LeftSection/InputSelectionSection/index.tsx
  src/components/MathQuill/index.tsx
  src/components/MathQuill/style.tsx
  src/index.tsx
  src/store/modules/index.ts
  src/store/modules/mathQuill.ts
Labels: :large_blue_diamond:Feature, :sunny:Frontend

#92 feature/#12 수식기호, 단위, 연산자 버튼 리스트를 한 줄 최대 6개씩 배치
  package-lock.json
  package.json
  src/components/Common/Button/index.tsx
  src/components/Common/LatexContent/style.tsx
  src/components/Header/index.tsx
  src/components/LeftSection/InputSelectionSection/InputBottomSelectionSection.tsx
  src/components/LeftSection/InputSelectionSection/InputTopSelectionSection.tsx
  src/components/LeftSection/InputSelectionSection/InputTopSelectionSvg.tsx
  src/components/LeftSection/InputSelectionSection/index.tsx
  src/components/LeftSection/InputSelectionSection/style.tsx
  src/constants/InputSection.ts
  src/utils/svg/leftsection/inputsection/arrow.svg
  src/utils/svg/leftsection/inputsection/division.svg
  src/utils/svg/leftsection/inputsection/figure.svg
  src/utils/svg/leftsection/inputsection/font.svg
  src/utils/svg/leftsection/inputsection/greece.svg
  src/utils/svg/leftsection/inputsection/inequality.svg
  src/utils/svg/leftsection/inputsection/minus.svg
  src/utils/svg/leftsection/inputsection/multiple.svg
  src/utils/svg/leftsection/inputsection/notoperator.svg
  src/utils/svg/leftsection/inputsection/plus.svg
  src/utils/svg/leftsection/inputsection/specialsymbol.svg
  src/utils/svg/leftsection/inputsection/unit.svg
Labels: ::cherry_blossom:: Style, :hammer:Refactor, :large_blue_diamond:Feature, :sunny:Frontend

#93 feat: clear 기능 구현
  src/components/MathQuill/index.tsx
  src/components/Toolbar/index.tsx
  src/components/index.tsx
  src/components/style.ts
  src/store/modules/mathQuill.ts
Labels: :large_blue_diamond:Feature, :sunny:Frontend

#94 MainSection 리팩토링 및 LaTeX 영역 Resizing 기능 구현 중
  src/components/Common/Svg/index.tsx
  src/components/Common/Svg/style.tsx
  src/components/LeftSection/InputSelectionSection/Box.tsx
  src/components/LeftSection/InputSelectionSection/index.tsx
  src/components/MainSection/LatexSection/Handle.tsx
  src/components/MainSection/LatexSection/index.tsx
  src/components/MainSection/LatexSection/style.tsx
  src/components/MainSection/MainSection.tsx
  src/components/MainSection/MainSectionStyle.ts
  src/components/MainSection/MainSectionTemplate.tsx
  src/components/MainSection/MathQuill/index.tsx
  src/components/MainSection/MathQuill/style.tsx
  src/components/MainSection/Tab/TabList.tsx
  src/components/MainSection/Tab/index.tsx
  src/components/MainSection/Tab/style.tsx
  src/components/Toolbar/AlignDropDown/AlignContent.tsx
  src/components/Toolbar/AlignDropDown/Button.tsx
  src/components/Toolbar/AlignDropDown/index.tsx
  src/components/Toolbar/AlignDropDown/style.tsx
  src/components/Toolbar/GraphButton/index.tsx
  src/components/Toolbar/index.tsx
  src/components/Toolbar/style.tsx
  src/components/index.tsx
  src/components/style.ts
  src/constants/InputSection.ts
  src/store/modules/fontAlign.ts
  src/store/modules/fontDecline.ts
  src/store/modules/index.ts
  src/utils/svg/leftsection/inputsection/decoration.svg
  src/utils/svg/leftsection/inputsection/galho.svg
  src/utils/svg/leftsection/inputsection/inputdraw.svg
  src/utils/svg/leftsection/inputsection/integral.svg
  src/utils/svg/leftsection/inputsection/limit.svg
  src/utils/svg/leftsection/inputsection/matrix.svg
  src/utils/svg/leftsection/inputsection/operator.svg
  src/utils/svg/leftsection/inputsection/pow.svg
  src/utils/svg/leftsection/inputsection/sigma.svg
  src/utils/svg/leftsection/inputsection/sin.svg
  src/utils/svg/toolbar/align-center.svg
  src/utils/svg/toolbar/align-left.svg
  src/utils/svg/toolbar/align-right.svg
Labels: :hammer:Refactor, :large_blue_diamond:Feature, :sunny:Frontend

#95 feature/#63 이미지 저장 기능 구현
  package-lock.json
  package.json
  src/components/Common/Button/index.tsx
  src/components/Common/LatexContent/style.tsx
  src/components/Header/index.tsx
  src/components/LeftSection/InputSelectionSection/InputBottomSelectionSection.tsx
  src/components/LeftSection/InputSelectionSection/InputTopSelectionSection.tsx
  src/components/LeftSection/InputSelectionSection/InputTopSelectionSvg.tsx
  src/components/LeftSection/InputSelectionSection/index.tsx
  src/components/LeftSection/InputSelectionSection/style.tsx
  src/constants/InputSection.ts
  src/utils/svg/leftsection/inputsection/arrow.svg
  src/utils/svg/leftsection/inputsection/division.svg
  src/utils/svg/leftsection/inputsection/figure.svg
  src/utils/svg/leftsection/inputsection/font.svg
  src/utils/svg/leftsection/inputsection/greece.svg
  src/utils/svg/leftsection/inputsection/inequality.svg
  src/utils/svg/leftsection/inputsection/minus.svg
  src/utils/svg/leftsection/inputsection/multiple.svg
  src/utils/svg/leftsection/inputsection/notoperator.svg
  src/utils/svg/leftsection/inputsection/plus.svg
  src/utils/svg/leftsection/inputsection/specialsymbol.svg
  src/utils/svg/leftsection/inputsection/unit.svg
Labels: :hammer:Refactor, :inbox_tray: Build, :sunny:Frontend

#101 feature/#63 이미지 저장 기능 구현 버그 수정
  src/components/Header/index.tsx
  src/components/LeftSection/InputSelectionSection/Box.tsx
  src/components/MainSection/LatexSection/Handle.tsx
  src/components/MainSection/LatexSection/index.tsx
  src/components/MainSection/LatexSection/style.tsx
  src/components/MainSection/MainSection.tsx
  src/components/MainSection/MainSectionStyle.ts
  src/components/MainSection/MainSectionTemplate.tsx
  src/components/MainSection/MathQuill/index.tsx
  src/components/MainSection/MathQuill/style.tsx
  src/components/MainSection/Tab/TabList.tsx
  src/components/MainSection/Tab/index.tsx
  src/components/MainSection/Tab/style.tsx
  src/components/MathQuill/index.tsx
  src/components/Toolbar/AlignDropDown/index.tsx
  src/components/Toolbar/FontColorDropdown/Button.tsx
  src/components/Toolbar/FontColorDropdown/index.tsx
  src/components/Toolbar/GraphButton/index.tsx
  src/components/Toolbar/index.tsx
  src/components/index.tsx
  src/components/style.ts
  src/hooks/.txt
  src/store/modules/getMathQuill.ts
  src/store/modules/index.ts
  src/store/modules/mathQuill.ts
Labels: :field_hockey: Fix, :hammer:Refactor, :sunny:Frontend

#103 Feature/#20/LaTeX영역 resizing 기능 적용 및 LaTeX Content 드래그앤드롭 기능 적용
  src/components/Common/LatexContent/index.tsx
  src/components/Common/LatexContent/style.tsx
  src/components/LeftSection/InputSelectionSection/InputBottomSelectionSection.tsx
  src/components/LeftSection/InputSelectionSection/InputTopSelectionSection.tsx
  src/components/LeftSection/InputSelectionSection/index.tsx
  src/components/LeftSection/InputSelectionSection/style.tsx
  src/components/LeftSection/MathSection/style.tsx
  src/components/LeftSection/TemplateSection/style.tsx
  src/components/MainSection/LatexSection/Handle.tsx
  src/components/MainSection/LatexSection/style.tsx
  src/components/MainSection/MainSection.tsx
  src/components/MainSection/MainSectionStyle.ts
  src/components/MainSection/MainSectionTemplate.tsx
  src/components/Toolbar/style.tsx
  src/components/style.ts
  src/store/modules/mathQuill.ts
  src/utils/colors.ts
  src/utils/svg/latex/x_button.svg
Labels: ::cherry_blossom:: Style, :large_blue_diamond:Feature, :sunny:Frontend

#107 feature/#65 html, css 저장 기능 구현
  src/components/Header/index.tsx
  src/components/LeftSection/InputSelectionSection/InputBottomSelectionSection.tsx
  src/components/LeftSection/InputSelectionSection/index.tsx
  src/components/LeftSection/InputSelectionSection/style.tsx
  src/components/MainSection/MainSection.tsx
  src/constants/InputSection.ts
  src/store/modules/getMathQuill.ts
  src/utils/savefile.ts
Labels: :hammer:Refactor, :large_blue_diamond:Feature, :sunny:Frontend

#108 Feature/#70 탭기능 구현 (추가, 이동)
  src/@types/index.d.ts
  src/components/MainSection/LatexSection/Handle.tsx
  src/components/MainSection/Tab/index.tsx
  src/components/Toolbar/index.tsx
  src/hooks/useInterval.ts
  src/store/modules/tab.ts
  src/utils/svg/latex/nullPreview.png
  webpack.config.js
Labels: :large_blue_diamond:Feature, :sunny:Frontend

#124 Feature/#63 이미지 저장 기능 수정
  package-lock.json
  package.json
  src/components/Header/index.tsx
  src/components/MainSection/CropSection.tsx
  src/components/MainSection/MainSection.tsx
  src/components/MainSection/MainSectionStyle.ts
  src/components/Toolbar/DrawerDropDown/index.tsx
  src/components/Toolbar/DrawerDropDown/style.tsx
  src/hooks/.txt
  src/store/modules/getMathQuill.ts
  src/utils/savefile.ts
  src/utils/svg/toolbar/erase.svg
  webpack.config.js
Labels: ::cherry_blossom:: Style, :hammer:Refactor, :inbox_tray: Build, :large_blue_diamond:Feature, :sunny:Frontend

#126 Feature/#72/Tab 삭제 기능 구현, 툴바 드롭다운 통일성 있게 변경
  src/components/Common/RoundButton/style.tsx
  src/components/Common/SvgButton/index.tsx
  src/components/Common/SvgButton/style.ts
  src/components/MainSection/LatexSection/Handle.tsx
  src/components/MainSection/LatexSection/style.tsx
  src/components/MainSection/Tab/PlusTab.tsx
  src/components/MainSection/Tab/TabList.tsx
  src/components/MainSection/Tab/index.tsx
  src/components/MainSection/Tab/style.tsx
  src/components/Toolbar/AlignDropDown/style.tsx
  src/components/Toolbar/BackgroundDropdown/index.tsx
  src/components/Toolbar/BackgroundDropdown/style.tsx
  src/components/Toolbar/DrawerDropDown/index.tsx
  src/components/Toolbar/DrawerDropDown/style.tsx
  src/components/Toolbar/FontColorDropdown/DropdownContent.tsx
  src/components/Toolbar/FontColorDropdown/style.tsx
  src/components/Toolbar/FontDropDown/FontButton.tsx
  src/components/Toolbar/FontDropDown/index.tsx
  src/components/Toolbar/FontDropDown/style.tsx
  src/components/Toolbar/ItalicButton/index.tsx
  src/components/Toolbar/OptionButtons/index.tsx
  src/components/Toolbar/ToolBar.tsx
  src/components/Toolbar/ToolBarStyle.ts
  src/components/Toolbar/ToolBarTemplate.tsx
  src/components/Toolbar/index.tsx
  src/components/Toolbar/style.tsx
  src/components/index.tsx
  src/components/style.ts
  src/store/modules/tab.ts
  src/utils/colors.ts
  src/utils/svg/background/background_icon.svg
  src/utils/svg/latex/x_button.svg
  src/utils/svg/tab/plus_icon.svg
  src/utils/svg/tab/x_icon.svg
  src/utils/svg/toolbar/erase.svg
  src/utils/svg/toolbar/graph.svg
Labels: :large_blue_diamond:Feature, :sunny:Frontend

#134 Feature/#130/왼쪽 영역 리사이징 기능 적용
  package-lock.json
  package.json
  src/components/Common/LatexContent/style.tsx
  src/components/Common/Title/style.tsx
  src/components/LeftSection/InputSelectionSection/InputBottomSelectionSection.tsx
  src/components/LeftSection/InputSelectionSection/InputTopSelectionSection.tsx
  src/components/LeftSection/InputSelectionSection/index.tsx
  src/components/LeftSection/InputSelectionSection/style.tsx
  src/components/LeftSection/LeftSection.tsx
  src/components/LeftSection/LeftSectionStyle.ts
  src/components/LeftSection/LeftSectionTemplate.tsx
  src/components/LeftSection/MathSection/style.tsx
  src/components/LeftSection/ResizingBar/index.tsx
  src/components/LeftSection/ResizingBar/style.ts
  src/components/LeftSection/SplitArea/index.tsx
  src/components/LeftSection/TempArea/index.tsx
  src/components/LeftSection/TempArea/style.ts
  src/components/LeftSection/TemplateSection/style.tsx
  src/components/MainSection/MathQuill/style.tsx
  src/components/index.tsx
  src/utils/colors.ts
Labels: :large_blue_diamond:Feature, :sunny:Frontend

#137 드래그앤드롭 버그 수정
  src/components/Common/LatexContent/index.tsx
  src/components/Common/LatexContent/style.tsx
  src/components/MainSection/LatexSection/style.tsx
  src/components/MainSection/MainSection.tsx
  src/components/MainSection/MainSectionStyle.ts
  src/components/MainSection/MathQuill/index.tsx
Labels: :field_hockey: Fix, :sunny:Frontend

#140 그림판 수정, 눈 애니메이션 효과 적용
  package-lock.json
  src/components/Common/Canvas/index.tsx
  src/components/Common/Canvas/style.tsx
  src/components/MainSection/MainSection.tsx
  src/components/MainSection/MainSectionStyle.ts
  src/components/MainSection/MainSectionTemplate.tsx
  src/components/Toolbar/DrawerDropDown/index.tsx
  src/components/Toolbar/DrawerDropDown/style.tsx
  src/store/modules/drawerDropdown.ts
  src/utils/setColor.ts
Labels: ::cherry_blossom:: Style, :hammer:Refactor, :large_blue_diamond:Feature, :sunny:Frontend

#143 그림판 수정, 애니메이션 눈 구현
  src/components/Common/Canvas/index.tsx
  src/components/Common/Canvas/style.tsx
  src/components/MainSection/MainSection.tsx
  src/components/MainSection/MainSectionStyle.ts
  src/components/MainSection/MainSectionTemplate.tsx
  src/components/MainSection/MathQuill/index.tsx
  src/components/MainSection/MathQuill/style.tsx
  src/components/Toolbar/BackgroundDropdown/index.tsx
  src/components/Toolbar/DrawerDropDown/index.tsx
  src/store/modules/backgroundDropdown.ts
  src/utils/backgroundAnimation.ts
Labels: ::cherry_blossom:: Style, :hammer:Refactor, :sunny:Frontend

#146 버그 수정
  src/components/Common/Canvas/index.tsx
  src/components/Common/Canvas/style.tsx
  src/components/MainSection/MainSection.tsx
  src/components/MainSection/MathQuill/index.tsx
  src/components/MainSection/MathQuill/style.tsx
  src/components/Toolbar/BackgroundDropdown/index.tsx
  src/components/Toolbar/DrawerDropDown/index.tsx
  src/components/Toolbar/FontDropDown/index.tsx
  src/components/Toolbar/ToolBarTemplate.tsx
  src/store/modules/drawerDropdown.ts
Labels: :field_hockey: Fix, :sunny:Frontend

#147 Feature/#138/graph desmos 라이브러리 적용
  package-lock.json
  package.json
  src/components/LeftSection/TemplateSection/index.tsx
  src/components/SubSection/index.tsx
  src/components/SubSection/style.ts
  src/components/Toolbar/DrawerDropDown/index.tsx
  src/components/index.tsx
  src/components/style.ts
  src/utils/colors.ts
  tsconfig.json
Labels: :field_hockey: Fix, :large_blue_diamond:Feature, :sunny:Frontend

#149 그림판 기능 구현
  src/components/MainSection/MainSection.tsx
  src/components/MainSection/MainSectionStyle.ts
  src/components/Toolbar/DrawerDropDown/index.tsx
  src/utils/setColor.ts
Labels: ::cherry_blossom:: Style, :large_blue_diamond:Feature, :sunny:Frontend

#150 feat: REDO, UNDO 기능 구현
  src/components/MainSection/Tab/index.tsx
  src/components/Toolbar/OptionButtons/index.tsx
  src/store/modules/mathQuill.ts
  src/store/modules/tab.ts
Labels: :field_hockey: Fix, :large_blue_diamond:Feature, :sunny:Frontend

#157 Feature/#148/header button
  src/components/Common/Button/style.tsx
  src/components/Common/SaveModeButton/index.tsx
  src/components/Common/SaveModeButton/style.tsx
  src/components/Header/SaveButtons.tsx
  src/components/Header/style.tsx
Labels: :large_blue_diamond:Feature, :sunny:Frontend

#167 modify: header 버튼 스타일 수정
  src/components/Header/index.tsx
  src/components/Header/style.tsx
Labels: ::cherry_blossom:: Style, :sunny:Frontend

#169 Feature/#30/ 왼쪽영역 기호 수식영역에 나타나도록 클릭이벤트 적용
  src/components/Common/Button/style.tsx
  src/components/Common/LatexSymbolContent/index.tsx
  src/components/Common/LatexSymbolContent/style.tsx
  src/components/LeftSection/InputSelectionSection/InputBottomSelectionSection.tsx
  src/components/LeftSection/MathSection/index.tsx
  src/constants/InputSection.ts
  src/constants/mathSection.ts
Labels: :large_blue_diamond:Feature, :sunny:Frontend

#170 저장 버튼 수정
  package-lock.json
  src/components/Header/SaveButtons.tsx
  src/components/Header/index.tsx
  src/components/Header/style.tsx
  src/components/MainSection/MainSection.tsx
  src/components/Toolbar/BackgroundDropdown/index.tsx
  src/components/Toolbar/DrawerDropDown/index.tsx
  src/hooks/useOutSideClick.ts
  src/store/modules/getMathQuill.ts
  src/utils/backgroundAnimation.ts
  src/utils/setColor.ts
Labels: ::cherry_blossom:: Style, :large_blue_diamond:Feature, :sunny:Frontend

#171 fix : 파일 이름 변경
  src/components/Toolbar/ToolBar.tsx
Labels: :field_hockey: Fix

#173 배경화면 테마 구현(비 애니메이션, 눈 애니메이션)
  src/components/Common/Button/style.tsx
  src/components/Common/Canvas/index.tsx
  src/components/Common/Canvas/style.tsx
  src/components/Common/DropDown/index.tsx
  src/components/Common/LatexContent/index.tsx
  src/components/Header/SaveButtons.tsx
  src/components/Header/index.tsx
  src/components/MainSection/MainSection.tsx
  src/components/Toolbar/BackgroundDropdown/index.tsx
  src/components/Toolbar/BackgroundDropdown/style.tsx
  src/components/Toolbar/DrawerDropDown/index.tsx
  src/store/modules/backgroundDropdown.ts
  src/store/modules/getMathQuill.ts
  src/utils/drawingRainAnimation.ts
  src/utils/drawingSnowAnimation.ts
  src/utils/svg/background/눈배경화면.jpg
  src/utils/svg/background/비배경화면.jpg
  src/utils/svg/header/logo.svg
Labels: ::cherry_blossom:: Style, :large_blue_diamond:Feature, :sunny:Frontend

#177 로고변경, 헤더 버튼 추가, alert 메세지 레이아웃 추가, Tab 버그 수정
  src/components/Alert/index.tsx
  src/components/Alert/style.ts
  src/components/Common/Button/style.tsx
  src/components/Common/SaveModeButton/style.tsx
  src/components/Header/SaveButtons.tsx
  src/components/Header/style.tsx
  src/components/LeftSection/MathSection/index.tsx
  src/components/LeftSection/TemplateSection/index.tsx
  src/components/LeftSection/TemplateSection/style.tsx
  src/components/MainSection/MainSection.tsx
  src/components/MainSection/MainSectionTemplate.tsx
  src/components/MainSection/Tab/index.tsx
  src/components/style.ts
  src/constants/mathSection.ts
  src/utils/svg/header/logo.svg
  src/utils/svg/leftsection/templatesection/down-arrow.svg
  src/utils/svg/leftsection/templatesection/up-arrow.svg
Labels: :field_hockey: Fix, :large_blue_diamond:Feature, :sunny:Frontend

#178 fix: 탭 너비로 인한 이슈 해결
  src/components/Common/Button/style.tsx
  src/components/Common/RoundButton/style.tsx
  src/components/Common/SaveModeButton/style.tsx
  src/components/Common/Title/style.tsx
  src/components/Common/ToolbarButton/style.tsx
  src/components/Header/style.tsx
  src/components/LeftSection/InputSelectionSection/style.tsx
  src/components/LeftSection/LeftSectionStyle.ts
  src/components/LeftSection/MathSection/style.tsx
  src/components/LeftSection/TemplateSection/style.tsx
  src/components/MainSection/LatexSection/style.tsx
  src/components/MainSection/MainSection.tsx
  src/components/MainSection/MainSectionStyle.ts
  src/components/MainSection/MainSectionTemplate.tsx
  src/components/MainSection/MathQuill/style.tsx
  src/components/MainSection/Tab/style.tsx
  src/components/SubSection/index.tsx
  src/components/SubSection/style.ts
  src/components/index.tsx
  src/components/style.ts
  src/style.ts
  src/utils/global-style.ts
Labels: ::cherry_blossom:: Style, :field_hockey: Fix, :sunny:Frontend, :umbrella: Modify

#179 버튼 수정에 따른 상태변화 주기
  public/favicon.ico
  src/components/Header/SaveButtons.tsx
  src/components/Header/index.tsx
  src/components/MainSection/CropSection.tsx
  src/components/Toolbar/DrawerDropDown/index.tsx
  src/store/modules/drawerDropdown.ts
  src/store/modules/getMathQuill.ts
Labels: ::cherry_blossom:: Style, :hammer:Refactor, :large_blue_diamond:Feature

#189 modify: 수식 객체에 isPossible 추가
  src/constants/mathSection.ts
Labels: :sunny:Frontend, :umbrella: Modify

#196 Feature/refactor merge 충돌 해결
  src/@types/colorType.ts
  src/MainPage.tsx
  src/components/Alert/index.tsx
  src/components/Alert/style.ts
  src/components/Common/DropDown/index.tsx
  src/components/Common/LatexContent/index.tsx
  src/components/Header/SaveButtons.tsx
  src/components/Header/index.tsx
  src/components/Header/style.tsx
  src/components/LeftSection/InputSelectionSection/InputBottomSelectionSection.tsx
  src/components/LeftSection/InputSelectionSection/InputTopSelectionSection.tsx
  src/components/LeftSection/MathSection/index.tsx
  src/components/LeftSection/TemplateSection/index.tsx
  src/components/MainSection/CropSection.tsx
  src/components/MainSection/MainSection.tsx
  src/components/MainSection/MathQuill/index.tsx
  src/components/MainSection/MathQuill/style.tsx
  src/components/MainSection/Tab/index.tsx
  src/components/Toolbar/AlignDropDown/index.tsx
  src/components/Toolbar/BackgroundDropdown/index.tsx
  src/components/Toolbar/FontColorDropdown/Button.tsx
  src/components/Toolbar/FontColorDropdown/index.tsx
  src/components/Toolbar/FontDropDown/index.tsx
  src/components/Toolbar/FontDropDown/style.tsx
  src/components/Toolbar/GraphButton/index.tsx
  src/components/Toolbar/ItalicButton/index.tsx
  src/components/Toolbar/PaintDropDown/index.tsx
  src/components/Toolbar/PaintDropDown/style.tsx
  src/components/Toolbar/ToolBar.tsx
  src/components/index.tsx
  src/mainPageStyle.ts
  src/store/configure.ts
  src/store/index.ts
  src/store/modules/alert.ts
  src/store/modules/backgroundDropdown.ts
  src/store/modules/drawerDropdown.ts
  src/store/modules/font-dropdown.ts
  src/store/modules/fontAlign.ts
  src/store/modules/fontColorDropdown.ts
  src/store/modules/fontDecline.ts
  src/store/modules/fontSizeDropdown.ts
  src/store/modules/getMathQuill.ts
  src/store/modules/graph.ts
  src/store/modules/index.ts
  src/store/modules/leftSection.ts
  src/store/modules/mathQuill.ts
  src/store/modules/paintDropdown.ts
  src/store/modules/saveMode.ts
  src/store/modules/tab.ts
  src/utils/colors.ts
  src/utils/localstorage.ts
Labels: :field_hockey: Fix, :hammer:Refactor

#195 store 디렉토리 리팩토링
  src/@types/colorType.ts
  src/MainPage.tsx
  src/components/Alert/index.tsx
  src/components/Alert/style.ts
  src/components/Common/DropDown/index.tsx
  src/components/Common/LatexContent/index.tsx
  src/components/Header/SaveButtons.tsx
  src/components/Header/index.tsx
  src/components/Header/style.tsx
  src/components/LeftSection/InputSelectionSection/InputBottomSelectionSection.tsx
  src/components/LeftSection/InputSelectionSection/InputTopSelectionSection.tsx
  src/components/LeftSection/MathSection/index.tsx
  src/components/LeftSection/TemplateSection/index.tsx
  src/components/MainSection/CropSection.tsx
  src/components/MainSection/MainSection.tsx
  src/components/MainSection/MathQuill/index.tsx
  src/components/MainSection/MathQuill/style.tsx
  src/components/MainSection/Tab/index.tsx
  src/components/Toolbar/AlignDropDown/index.tsx
  src/components/Toolbar/BackgroundDropdown/index.tsx
  src/components/Toolbar/FontColorDropdown/Button.tsx
  src/components/Toolbar/FontColorDropdown/index.tsx
  src/components/Toolbar/FontDropDown/index.tsx
  src/components/Toolbar/FontDropDown/style.tsx
  src/components/Toolbar/GraphButton/index.tsx
  src/components/Toolbar/ItalicButton/index.tsx
  src/components/Toolbar/PaintDropDown/index.tsx
  src/components/Toolbar/PaintDropDown/style.tsx
  src/components/Toolbar/ToolBar.tsx
  src/components/index.tsx
  src/mainPageStyle.ts
  src/store/configure.ts
  src/store/index.ts
  src/store/modules/alert.ts
  src/store/modules/backgroundDropdown.ts
  src/store/modules/drawerDropdown.ts
  src/store/modules/font-dropdown.ts
  src/store/modules/fontAlign.ts
  src/store/modules/fontColorDropdown.ts
  src/store/modules/fontDecline.ts
  src/store/modules/fontSizeDropdown.ts
  src/store/modules/getMathQuill.ts
  src/store/modules/graph.ts
  src/store/modules/index.ts
  src/store/modules/leftSection.ts
  src/store/modules/mathQuill.ts
  src/store/modules/paintDropdown.ts
  src/store/modules/saveMode.ts
  src/store/modules/tab.ts
  src/utils/colors.ts
  src/utils/localstorage.ts
Labels: :hammer:Refactor

#198 Refactor: 폴더명 수정
  src/components/Toolbar/AlignDropdown/AlignContent.tsx
  src/components/Toolbar/AlignDropdown/Button.tsx
  src/components/Toolbar/AlignDropdown/index.tsx
  src/components/Toolbar/AlignDropdown/style.tsx
Labels: :hammer:Refactor

#199 Refactor: 폴더명 수정
  src/components/LeftSection/ResizingArea/MathSection/ButtonList.tsx
  src/components/LeftSection/ResizingArea/MathSection/index.tsx
  src/components/LeftSection/ResizingArea/MathSection/style.tsx
  src/components/LeftSection/ResizingArea/TemplateSection/index.tsx
  src/components/LeftSection/ResizingArea/TemplateSection/style.tsx
  src/components/LeftSection/ResizingArea/index.tsx
  src/components/Toolbar/PaintDropdown/index.tsx
  src/components/Toolbar/PaintDropdown/style.tsx
Labels: :hammer:Refactor

#201 modify: 그래프 영역, 드롭다운 영역 z-index 변경
  src/components/SubSection/style.ts
  src/components/Toolbar/AlignDropdown/style.tsx
  src/components/Toolbar/BackgroundDropdown/style.tsx
  src/components/Toolbar/FontColorDropdown/style.tsx
  src/components/Toolbar/FontSizeDropdown/style.tsx
  src/components/Toolbar/PaintDropdown/style.tsx
Labels: :field_hockey: Fix, :sunny:Frontend

#202 사칙연산 드랙앤드롭 문제 해결, 알람 팝업 배경 투명하게 수정
  src/components/Alert/style.ts
  src/components/LeftSection/InputSelectionSection/InputBottomSelectionSection.tsx
  src/constants/InputSection.ts
Labels: :field_hockey: Fix, :sunny:Frontend

#203 fix: 경로 대소문자 수정, console.log 삭제
  src/components/Common/DropDown/index.tsx
  src/components/MainSection/Tab/index.tsx
  src/components/Toolbar/ToolBar.tsx
Labels: :field_hockey: Fix, :sunny:Frontend

#209 애니메이션 소스 수정
  src/components/Toolbar/BackgroundDropdown/index.tsx
  src/utils/drawingSnowAnimation.ts
Labels: ::cherry_blossom:: Style, :hammer:Refactor

#210 font color 드롭다운 메뉴 z-index 추가 및 템플릿 수식 드래그앤드롭 기능 수정
  src/components/Alert/style.ts
  src/components/LeftSection/ResizingArea/TemplateSection/index.tsx
  src/components/Toolbar/FontColorDropdown/style.tsx
  src/constants/templateSection.ts
Labels: :field_hockey: Fix, :sunny:Frontend

#213 refactor : 불필요 코드 제거
  src/components/LeftSection/ResizingArea/MathSection/index.tsx
  src/components/MainSection/Tab/index.tsx
  src/components/MainSection/Tab/style.tsx
  src/utils/localstorage.ts
Labels: :field_hockey: Fix

#215 Feature/fix redo
  src/components/LeftSection/BottomWhiteSpace/style.ts
  src/components/LeftSection/InputSelectionSection/style.tsx
  src/components/LeftSection/ResizingArea/MathSection/style.tsx
  src/components/LeftSection/ResizingArea/TemplateSection/style.tsx
  src/components/MainSection/MathQuill/style.tsx
  src/components/Toolbar/BackgroundDropdown/index.tsx
  src/components/Toolbar/BackgroundDropdown/style.tsx
  src/components/Toolbar/PaintDropdown/index.tsx
  src/components/Toolbar/PaintDropdown/style.tsx
  src/components/style.ts
  src/constants/mathSection.ts
Labels: ::cherry_blossom:: Style, :field_hockey: Fix, :hammer:Refactor
